[main]
mode = "client" # "server" or "client"
secret = "not_simply_password"
id = "XXXXXXXX-XXXX-XXXX-XXXX-XXXXXXXXXXXX" # for client mode
protocol = "tcp"    # or "udp", "quic", "tls", "dtls", "kcp"
debug = false       # fast switch to all log levels to debug
remote_addr = "hostname.or.ip"
remote_port = 12345
#local_addr = "local.ip.address" # listen on the IP (for server mode)
#local_port = 12345 # listen on the port (for server mode)
attempts = 1                    # 0 means infinity
retry_delay = 5
[crypt]
engine = "aes-cbc"
sign_engine = "ed25519"
[tls]
cert_file = ""
key_file = ""
[tun]
tun_addr = ["10.0.0.10/24","fd11::10/64"]
mtu = 1420
name = "snake"
[socks5]
enabled = false
port = 1080
username = ""
password = ""
[log]
file = ""      # log file path, empty means stdout
nocolor = false  # disable color output on stdout
main = "Error"
protocol = "Debug"
network = "Warnings"
route = "Info"
crypt = "Info"
clients = "Info"
tun = "info"
transport = "info"
socks5 = "info"