[main]
mode = "client"
secret = "not_simply_password"
id = "XXXXXXXX-XXXX-XXXX-XXXX-XXXXXXXXXXXX"
protocol = "tcp"
debug = false
remote_addr = "hostname.or.ip"
remote_port = 12345
[tun]
tun_addr = ["10.0.0.10/24","fd11::10/64"]
mtu = 1420
name = "snake"
[log]
main="Error"
protocol="Debug"
network="Warnings"
route="Info"
crypt="Info"
clients="Info"
tun="info"
